logging:
  level: DEBUG

datasource:
  master:
    jdbcUrl: root:123@tcp(localhost:3306)/ordercenter?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  slave:
    jdbcUrl: root:123@tcp(localhost:3306)/ordercenter?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  config:
    socketTimeout: 60

redis:
  addr: "127.0.0.1:56379"

gin:
  port: ":28080"

microservice:
  account: "http://localhost:48080"